COURSE_ACTS(COURSE_BOB, _(" 1 CAMPO DE LOS BOB-OMB"),
       _("GRAN BOB-OMB EN LA CIMA")                , _("EL DESAFおO DE KOOPA EL VELOZ")       , _("DISPARA A LA ISLA DEL CIELO"),
       _("EN BUSCA DE 8 MONEDAS ROJAS")            , _("EL VUELO DE MARIO")                   , _("DA RIENDA SUELTA A CHOMP CADENAS"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTALEZA DE PIEDRA"),
       _("DERROCA A ROCO")                         , _("EN LO ALTO DE LA FORTALEZA")          , _("LANZADO HACIA EL CIELO"),
       _("MONEDAS ROJAS EN LA ISLA FLOTANTE")      , _("CAおDA LIBRE A LA ISLA ENJAULADA")    , _("A CAけONAZOS CONTRA EL MURO"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAHおA DEL CAPITうN"),
       _("EL BOTおN DEL BARCO HUNDIDO")             , _("LA MORENA LA VIGILA")                , _("TESORO DE LA CUEVA DEL OCえANO"),
       _("MONEDAS ROJAS EN LA NAVE A FLOTE")       , _("APUNTA A LO ALTO DE LA AGUJA")        , _("QUE NO TE LLEVE LA CORRIENTE"))

COURSE_ACTS(COURSE_CCM, _(" 4 MONTE HELADO"),
       _("AL FINAL DEL TOBOGうN")                   , _("PEQUEけO PINGくINO PERDIDO")           , _("EL MうS RうPIDO DEL HIELO"),
       _("8 MONEDAS ROJAS EN LA MONTAけA")          , _("MUけECO DE NIEVE SIN CABEZA")          , _("PATADA EN LA PARED DE MARIO"))

COURSE_ACTS(COURSE_BBH, _(" 5 MANSIかN ENCANTADA"),
       _("CAZAFANTASMAS")                          , _("EL TIOVIVO DEL GRAN BOO")            , _("EL SECRETO QUE GUARDAN LOS LIBROS"),
       _("LAS 8 ENDIABLADAS MONEDAS ROJAS")        , _("EL BALCかN DEL GRAN BOO")            , _("へOJO EN LA HABITACIかN SECRETA!"))

COURSE_ACTS(COURSE_HMC, _(" 6 CUEVA DEL LABERINTO"),
       _("EL MONSTRUO DE LA CUEVA DEL LAGO")       , _("EL CAMINO DE LAS 8 MONEDAS ROJAS")   , _("へMARIO, EL HOMBRE DE HIERRO!"),
       _("EN EL LABERINTO TかXICO")                , _("LA OTRA SALIDA DEL LABERINTO")       , _("EN LAS BOLAS DE PIEDRA"))

COURSE_ACTS(COURSE_LLL, _(" 7 TIERRA DEL FUEGO"),
       _("LAVA AL GRAN BRONCO")                    , _("TRES TRISTES BRONCOS")               , _("EL PUZLE DE LAS 8 MONEDAS"),
       _("へTRONCO, CかMO QUEMA!")                   , _("へEN EL CORAZかN DEL VOLCうN!")           , _("ESCALADA EN EL VOLCうN"))

COURSE_ACTS(COURSE_SSL, _(" 8 ARENAS ARDIENTES"),
       _("EN LAS GARRAS DEL PAJARRACO")            , _("EN LO ALTO DE LA PIRうMIDE")          , _("EL SECRETO DE LA PIRうMIDE"),
       _("CORONA LOS CUATRO PILARES")              , _("8 MONEDAS ROJAS EN VUELO LIBRE")      , _("LABERINTO DE LA PIRうMIDE"))

COURSE_ACTS(COURSE_DDD, _(" 9 EL GRAN MUELLE"),
       _("SOBRE EL SUBMARINO")                     , _("COFRES EN LA CORRIENTE")             , _("MONEDAS ROJAS, POSTE A POSTE"),
       _("ATRAVESANDO LA CORRIENTE")               , _("TRAS LA ESTELA DE LA MANTA")         , _("DENTRO DE LA JAULA"))

COURSE_ACTS(COURSE_SL, _("10 PAおS DE HIELO"),
       _("SOBRE LA CABEZA DEL MUけECO")             , _("EL DUELO DEL HIELO")                 , _("MうS ALLう DEL LAGO HELADO"),
       _("GIRA DESDE LA FUENTE HELADA")            , _("MONEDAS ROJAS EN EL IGLき")           , _("EN EL IGLき"))

COURSE_ACTS(COURSE_WDW, _("11 CIUDAD ESPONJA"),
       _("へMOJANDO PLATAFORMAS!")                  , _("EN LO MうS ALTO DE LA CIUDAD")        , _("LOS 5 NきMEROS SECRETOS"),
       _("ASCENSOR EXPRESO: へDATE PRISA!")         , _("EL ROJO BRILLO DE LA CIUDAD")        , _("へCARRERA RうPIDA POR LA CIUDAD!"))

COURSE_ACTS(COURSE_TTM, _("12 MONTE ESCARPADO"),
       _("ESCALA LA MONTAけA")                      , _("EL MISTERIO DE LA JAULA DEL MONO")   , _("MONEDAS ROJAS EN LOS SOMBREROS"),
       _("EL TOBOGうN MISTERIOSO")                  , _("DETRうS DE LA CASCADA")               , _("DISPARADO AL CHAMPIけかN SOLITARIO"))

COURSE_ACTS(COURSE_THI, _("13 ISLA CAMBIANTE"),
       _("SIN MIEDO CONTRA LAS FLORES PIRAけA")     , _("EN LO ALTO DE LA ISLA GIGANTE")      , _("REVANCHA DE KOOPA EL VELOZ"),
       _("CINCO PEQUEけOS SECRETOS")                , _("LAS MONEDAS ROJAS DE FLORUGA")       , _("DALE A FLORUGA UNA LECCIかN"))
 
COURSE_ACTS(COURSE_TTC, _("14 RELOJ TIC TOC"),
       _("ATERRIZAR EN LA JAULA")                  , _("EL FOSO Y EL PえNDULO")               , _("UNA MANILLA, POR FAVOR"),
       _("PICA A ROCA PICUDA")                     , _("LAS BARRAS Y BARRERAS DEL TIEMPO")    , _("PARA EL TIEMPO DE MONEDAS ROJAS"))

COURSE_ACTS(COURSE_RR, _("15 CAMINO DEL ARCO IRIS"),
       _("TRAVESおA AL ARCO IRIS")                  , _("EL CASかN CELESTIAL")                 , _("LAS MONEDAS DEL LABERINTO VERTICAL"),
       _("DESPUえS DEL VAIVえN")                    , _("EL SECRETO DE LAS PIRうMIDES")        , _("EN ALGきN LUGAR DEL ARCO IRIS"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER EN LAS TINIEBLAS"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER EN LA LAVA"))
SECRET_STAR(COURSE_BITS, _("   BOWSER EN EL CIELO"))
SECRET_STAR(COURSE_PSS, _("   EL TOBOGうN DE LA PRINCESA"))
SECRET_STAR(COURSE_COTMC, _("   CAVERNA DEL GORRO METうLICO"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DEL GORRO ALADO"))
SECRET_STAR(COURSE_VCUTM, _("   FOSO DEL GORRO INVISIBLE"))
SECRET_STAR(COURSE_WMOTR, _("   SOBRE LOS ARCO IRIS"))
SECRET_STAR(COURSE_SA, _("   EL ACUARIO SECRETO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("LAS ESTRELLAS SECRETAS"))

EXTRA_TEXT(0, _("へUNA ESTRELLA SECRETA!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
